POST localhost/stm/order/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE1OTE3MTIwMjgsImV4cCI6MTU5MTcxNTYyOH0.YRb9LvLAKm9xHNH3b1UdzCo6CHDQ9jNZbynukkzIMUM

{
  "sourceCurrency": "BYN",
  "targetCurrency": "USD",
  "amount": "8099",
  "fee": "2.44",
  "userEmail": "vladislav.yurkevich@softclub.by"
}

###